# Generated by Django 4.1.1 on 2022-10-09 15:54

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=3)),
                ("name", models.CharField(max_length=256)),
                ("e_mail", models.EmailField(blank=True, max_length=128)),
                ("phone", models.CharField(blank=True, max_length=128)),
                ("city", models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                models.F("code"), name="uniq_person_code"
            ),
        ),
    ]
