# Generated by Django 4.1.2 on 2022-10-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="sections",
            field=models.ManyToManyField(
                through="team.TeamMembership", to="team.teamsection"
            ),
        ),
    ]
