# Generated by Django 4.1.2 on 2022-10-30 09:14

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            features=[
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
                verbose_name="body",
            ),
        ),
    ]
