name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:        
      - v*
      
defaults:
 run:
  working-directory: ./av_backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag av-backend:test-01
      #run: docker build . --file av_backend/Dockerfile --tag av-backend:$(date +%s)
    - name: Push the image to repo
      run: docker push ghcr.io/vhk-cr/av-backend:test-01
