name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:        
      - v*
      
defaults:
 run:
  working-directory: ./av_backend

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/vhk-cr/av-backend
      IMAGE_TAG: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${IMAGE_NAME}:${IMAGE_TAG}
      #run: docker build . --file av_backend/Dockerfile --tag vhk-cr/av-backend:$(date +%s)
    - name: Push the image to repo
      run: docker push ${IMAGE_NAME}:${IMAGE_TAG}
