# Generated by Django 4.1.1 on 2022-10-09 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamSection",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "uuid",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=256)),
                ("e_mail", models.EmailField(blank=True, max_length=128)),
                ("phone", models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddConstraint(
            model_name="teamsection",
            constraint=models.UniqueConstraint(
                models.F("code"), name="uniq_section_code"
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_sections",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="member_persons",
                to="team.teamsection",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                models.F("person"), models.F("section"), name="uniq_team_membership"
            ),
        ),
    ]
